### ISSUE TITLE
Choosing an Arduino variant to order

### ISSUE THREAD

**Issue by joshcomley** [Zer0-bit/gaggiuino#171]
On the [link provided](https://www.aliexpress.com/item/4000903444456.html?spm=a2g0s.9042311.0.0.1b8c4c4dzBsUSa) there are some variations, and in all other hardware listings the variant is very handily specified.

So I'm wondering does it matter which of these I order? Can I order the USB-C one without issue?

![image](https://user-images.githubusercontent.com/820534/150696758-989c8ead-48d5-4d43-82a6-92346a9c76d7.png)

Thanks for this project!

**Comment by shigadeyo** [comment]
> On the [link provided](https://www.aliexpress.com/item/4000903444456.html?spm=a2g0s.9042311.0.0.1b8c4c4dzBsUSa) there are some variations, and in all other hardware listings the variant is very handily specified.
> 
> So I'm wondering does it matter which of these I order? Can I order the USB-C one without issue?
> 
My understanding is yes and I'm pretty sure that Zer0-bit stated in the Discord that he uses the USB-C one. I would have done the same, but found out later that the the only real difference in them is the connector option.

**Comment by shigadeyo** [comment]
Found it! Here is the link to the comment about this in the Discord channel - https://discord.com/channels/890339612441063494/890339612441063497/895691100201844806

**Comment by Zer0-bit** [comment]
Not an issue.
