### ISSUE TITLE
Pump not stopping after flush mode switched off

### ISSUE THREAD

**Issue by banoz** [Zer0-bit/gaggiuino#238]
setPumpToRawValue(0) needs to be added to the following `else` block
https://github.com/Zer0-bit/gaggiuino/blob/5be9fac649ffef134cfd4a302a3fd857ddde293c/src/gaggiuino.ino#L686-L693
otherwise the pump keeps blasting even after the flush mode switched off, in case the pump is not physically being disconnected by the brew switch.

**Comment by Zer0-bit** [comment]
Thx for raising this issue, added it to the nano  ranch and will create a new release soon.
