### ISSUE TITLE
Pressure?

### ISSUE THREAD

**Issue by spoetnik** [Zer0-bit/gaggiuino#29]
The readme mentions pressure in the descale function:

  flush - 10s x 5 at 2bar
  flush - 20s x5 at 1 bar
  idle  - 5min at 0 bar

There is no pressure gauge in this project. How does it know the pressure? Is it calculated from a baseline, and what is the baseline? A 9 bar modification or a stock Gaggia?

**Comment by Zer0-bit** [comment]
The baseline is 9bar  and atm  it's calculated from this baseline albeit I'm not expecting it to be overly precise still pretty sure im fairly close but once i get the gauge finally delivered I'll calibrate the dimmer output accordingly.

**Comment by spoetnik** [comment]
You are right. No need for complexity.
