### ISSUE TITLE
ADS 12 bit math issue

### ISSUE THREAD

**Issue by banoz** [Zer0-bit/gaggiuino#297]
https://github.com/Zer0-bit/gaggiuino/blob/b6976fbc3cc6afce9e3b1db21c8e0070ab65062f/src/peripherals/pressure_sensor.cpp#L32

needs to be like this

`    currentPressure = (ADS.getValue() - 166) / 111.11f; // 12bit`

**Comment by Zer0-bit** [comment]
Will change, thx.
