### ISSUE TITLE
Image links broken in Readme

### ISSUE THREAD

**Issue by maurera** [Zer0-bit/gaggiuino#311]
Hello,

First off - thanks for the work on this project! I've just bought a Gaggia Classic Pro and already excited to try this. A couple issues:
1. Most of the pictures linked from the Readme in this repo are broken. Are these pictures available elsewhere?
2. There are some slight differences in the parts list in the Readme vs the website (https://gaggiuino.github.io/#/). Eg included in the readme but not the website is "Hall Current Sensor Module ACS712 - 20A". Which source the most up to date? (Since aliexpress has notoriously slow shipping to Canada, I want to make sure I order all the right parts 😄) 

Broken picture looks like this, along with where the direct link goes:
<img width="1685" alt="image" src="https://user-images.githubusercontent.com/10040349/197289357-04d89a30-0779-46b5-b1b4-a4e4253c62ee.png">

Thanks again for the great work!

Edit:
- Looks like I was looking at an old release here (I think somehow I got linked there from google) - https://github.com/Zer0-bit/gaggiuino/blob/release-0.2.2/README.md
- New install instructions appear to have far less detail here https://gaggiuino.github.io/#/
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/10040349/197294611-ba3d0c53-70c9-40ea-896d-9ce26e5d3dad.png">
- The previous install instruction pictures could still be useful, for the steps that overlap, in case someone still has access to the image files!

Edit 2:
- There's some more detailed looking documentation here! https://github.com/Zer0-bit/gaggiuino/tree/release-nano-final-v4/wiki. Maybe we can link this in the main Readme.md?

Edit 3
- Actually it looks like the wiki folder was deleted from the main repo...

**Comment by Zer0-bit** [comment]
The only resource you should check is the website, wiki is dead long ago.
