### ISSUE TITLE
Non-free license

### ISSUE THREAD

**Issue by TechnologyClassroom** [Zer0-bit/gaggiuino#431]
I saw your tool mentioned in [arstechnica](https://arstechnica.com/gadgets/2023/03/great-espresso-isnt-hard-enough-so-heres-a-diy-open-source-machine-for-it/). The article says gaggiuino is open source, but the license says it is only for non-commercial usage. This reporting error is not your fault.

Non-commercial (NC) clauses are non-free as they are not free software according to the [FSF](https://www.gnu.org/philosophy/free-sw.html#selling), open source according to the [OSI](https://opensource.org/osd#free-redistribution), or free culture according to [Freedom Defined](https://freedomdefined.org/Definition).  I would recommend using CC-BY-SA-4.0, CC-BY-4.0, or CC-0-1.0 instead which are free culture Creative Commons licenses.

**Comment by Zer0-bit** [comment]
Thx for raising the concern, i'll look into it.
