### ISSUE TITLE
[Web Interface] TypeScript?

### ISSUE THREAD

**Issue by ckifer** [Zer0-bit/gaggiuino#471]
React and web development standards have been moving towards TypeScript as a rule for a few years now. JavaScript only projects tend to lead to issues down the road, especially when you have consumers (even if the consumers are just deploying/running their own copy).

Strongly typed languages (even in the web world) help with a multitude of things - developer experience, better autocomplete, assurance in what you are getting when variables are accessed, the same result at the end of the day, etc.

Any reasons why the web-interface isn't using TS? If not would a refactor be welcomed?

**Comment by Zer0-bit** [comment]
No reason tbh, first time touching this shit so it's basically learning this as i go, to me personally there's basically no difference which language to choose since gonna need to get a grip on either anyway.

**Comment by kstam** [comment]
No issues with a refactor either if you can be bothered :) I like Typescript as a language. Just couldn't be bothered to do all the type definitions when I was starting it.

**Comment by ckifer** [comment]
Cool 

I started moving things to vite (https://vitejs.dev/) because this ejected Create React App setup will become relatively unmanageable over time (large, unreadable config files, unneeded dependencies, etc) and it is no longer recommended by the React team. 

Let me know if thats over-stepping, but essentially we end up with the same thing as before + TypeScript support/TypeScript first + faster dev server (vite has much better HMR) + easier configuration structure

results in the same proxy, same functionality, less bloat
![image](https://github.com/Zer0-bit/gaggiuino/assets/25180830/66e33bcd-4934-48a0-b630-27cb89ef3e52)
![image](https://github.com/Zer0-bit/gaggiuino/assets/25180830/8ad1f010-6ad0-4801-9af9-0430282af3f8)

**Comment by Zer0-bit** [comment]
Issue linked to an already merged PR, closing.
