### ISSUE TITLE
Optimize Nextion display RAM usage

### ISSUE THREAD

**Issue by Tazmania0** [Zer0-bit/gaggiuino#530]
Hi, 

I really like this project. I'm working on adapting the functionality to respect the hardware of Gaggia Classic V2 (SS boiler and no solenoid valve).
I saw your announcement that you are moving project to new UI mainly because of insufficient resources of Nextion display. 
Recently I found that you can free sufficient amount of RAM (approximately 230 bytes). 
In Nextion Editor all text elements are with predefined length of 50 bytes and respectively so much RAM is reserved for each element. The same applies for all elements with text properties. In brewGraph page, I trimmed the texts and buttons to corresponding length of strings and I ended with:

**Page:brewGraph Memory Occupied:1248+2104=3352**

Which leaves enough RAM for further customization. 

I'm not sure if that matters much, but probably can help other builders to adapt the existing Nextion screen UI that suits their needs.  
Thank you again for your efforts in this project!!!

**Comment by Zer0-bit** [comment]
Hi - nextion is being dropped not because of resources limitations alone but because it's framework is very limited in capabilities and hinders any sort of future improvements.
