### ISSUE TITLE
Question: Power 220V thru DB15 connectors?

### ISSUE THREAD

**Issue by spoetnik** [Zer0-bit/gaggiuino#75]
I love the idea of using connectors. Do you run 220V thru the DB15 connector? Or only data cables?
Do you house the dimmer and current sensor in the coffee machine, or in the printed housing?

I think running 220V from the dimmer, and current-sensor from the 3D printed housing thru the DB15 connector to machine is a bit sketchy....

**Comment by LikeableBump** [comment]
There is a separate enclosure in the machine that houses the high voltage components. The only power that goes through the db15 connector is 5v, and data.
