### ISSUE TITLE
Best place to leave the USB charger?

### ISSUE THREAD

**Issue by dlime** [Zer0-bit/gaggiuino#79]
I'm undecided on where to leave the USB charger for Arduino. 
Whether inside/outside the back of the machine :)

Outside:
- look uglier
- practical for Arduino code updates
- more safe in terms of water leaks / contact 

Inside:
- neat look
- risk of getting wet
- less practical for updating Arduino code

Did you already experiment with the different possibilities?
Where did you left yours?

**Comment by Zer0-bit** [comment]
> I'm undecided on where to leave the USB charger for Arduino. Whether inside/outside the back of the machine :)
> 
> Outside:
> 
> * look uglier
> * practical for Arduino code updates
> * more safe in terms of water leaks / contact
> 
> Inside:
> 
> * neat look
> * risk of getting wet
> * less practical for updating Arduino code
> 
> Did you already experiment with the different possibilities? Where did you left yours?

Please don't create github issues about this type of stuff, there's a discord server created to discuss installation troubles and general ideas, issues are mostly for code issues or code improvement ideas.

**Comment by Zer0-bit** [comment]
Btw the answer you're looking for has been answered and showed in pictures on the discord server, as LikeableBump has posted pictures on how he integrated all with db15 connectors.

**Comment by dlime** [comment]
> > I'm undecided on where to leave the USB charger for Arduino. Whether inside/outside the back of the machine :)
> > Outside:
> > 
> > * look uglier
> > * practical for Arduino code updates
> > * more safe in terms of water leaks / contact
> > 
> > Inside:
> > 
> > * neat look
> > * risk of getting wet
> > * less practical for updating Arduino code
> > 
> > Did you already experiment with the different possibilities? Where did you left yours?
> 
> Please don't create github issues about this type of stuff, there's a discord server created to discuss installation troubles and general ideas, issues are mostly for code issues or code improvement ideas.

All right see you on Discord. Decided to ask it here since up till now I've seen both HW/SW questions in Issues 🤷

**Comment by Zer0-bit** [comment]
I wasn't trying to come up arrogant btw, i think it's a issue with trying to express yourself over text on the internet lol
